version: '3.8'

services:
  app:
    build: .
    container_name: imobi-facil
    ports:
      - '8081:8081'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
